version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
#    volumes:
#      - .storage\mssql-server:/var/opt/mssql/data